language: node_js
node_js:
- '5.6'
env:
  global:
  - GH_REF=github.com/mwaylabs/uikit
  - GH_USER=mwaysolutions
  - secure: sIApAq0PwkRvRC3X5cOGE4BHuL+QZrbOZAo8wT14sQj3XueAFN2sXnb+SQwFPAVudv6NvWOpgrMNhoG/PpOL+r+v5gNWzVUBbcsYpNbkpFK3wmlc8Cu+uObrExnOXk97IiUGI05lZC5Xm6YiV9+XXAjsn2H91hu6cS++CcaNw7nb5qmpbRDghxr5rbhc0kigDf6V0Vg16RCaFUm8//CmTBnEVFErNIeO+uRW8OsIJRMObvR+ZCSIORAeuYu+/W7f6rv+PpTDDP/og0m4gcwi8tPzY4IOYMQQ1WWx7dRi7JBxqtGTyV1h4ojgDX764W5HjB2SVppwdy2QfyHAMxW2qoHseO7ajbrBgDDtlXptYK49tfT1cMsH+b4wTOhMI+KeviFFB+kz5n9umwEN++7p2vTFyCFDXmMPYjguV8FwYN03Fchm96U84IMJ2BEaOOODsHO2RMU7SJqMQo63WjYX1SA+xmTtR73EDRuemGyAw/S7Mwk0wJKTVdKRDNvQD7MqkL8xu2sBsOhPaaYll+WPMnJ9Mv+Nf2orLz4mhTPGhcVr2wVrixslNDAFYElWWMgEkkZGy8B7kcc3Fyeu/tAZE8s9jgYm1+13F6XVvXb2s6qUQDFXOiyt/YqP3LsMgi9V0XVC9Vj9nrjXWKFGgx0hAxaMN/m9Kl8cOJP0Q7CIcag=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma
- bower install
deploy:
  - provider: script
    script: npm run release -- --buildNumber $TRAVIS_BUILD_NUMBER --commitHash $TRAVIS_COMMIT
    skip_cleanup: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: releases 
    api_key: 
      secure: EM4Y3vAyu55VHQCnblSf2A7BZC+lrm6SjbfdWihQ/8dTF/btXhfVZGGJypslEUEDa2D+usPZs3iSY6yioVk/b2hHT5CWJxnZh+SoxS65dgCt6TV4B52+/ikEJiEdukTuubDScAI5vIE6zcVbkTAvyevqVpQUuokxiCJgNd6rq3fkNCOcKF5unXn6O0SwDtkPCyBlPTiO6+SCGOfx7ZmeYjw9LOT/WnwrJYsIbNbpPnPEym8ULYJZjjizkGfj9dtcWRdViBC1DEnhVqf9WGqABgkH2kVJOmHjtY3pGBomwdQPBOsPGLv4z8nqiy3MMIV2h9cbSCghqjSyC8EkU3YFC+a+DAWydm9bRTa2+vSopwt/WmIAHrj+VkUa7sW4xFJnqNa9AeD8E6qsVsVDi+hnj0DT0RZ+x65m5cpeRD0XdL4t1T8Mm2pCOo7gA3L+nYe3hVZGrM82Jd5rOqwQkOfNrcpuKf3TIgIIrkVpPV0ApElKbSUnhWQtIy9IY4wP6kKW84i6x7HQC/q87NhVq8g9pNscLz9PRjnqd2mb1CdjKTw1BbM9GQRCWp0r8aH1eso9nQOHAgTYsswx3EkX2AuhuOBQFpJ7D8DH383b/9PrIkF7ZXxR3bJ5WUSi38gc6O0aN7ogyQIYk2UC2UzX/V9O9RcRdFmPtKKJfdkFmdWAABk=
    file: zip/*.zip
    skip_cleanup: true 
    file_glob: true 
    on: 
      tags: true
  - provider: npm
    email: a.zarges@mwaysolutions.com
    api_key:
      secure: RmhcogeQ5XJ5LCG7v9LRd3WOB6BJW0b+7YE3+dk5UkfMgYVIu3sKccWfvv2+O0RV0+5VG8qyuJ5AK07AzVWIW+UIA/slaI9dU7rcl2/+sUT2tmQ0CTF44wvrbfB5e921zfxZTM7iqG4UxRea2RHtjQDi1nHRs9GsMicv/IN8lFFK7NZQv3QeOT23sewE7STXg6cbhSzQh1In3l+wOzv7+e8PjK9NFCOCXmSSKp2keTgFu9sdH8rLUQAo3ervSzgQW0Qtreey7IloD7vKgZP6WpI5Xj4+m6ck+D5z6QZ8+ht3u+7y8IHLJAmswyJcha0j8e18dMeZxa5qZuwzWu1r1Jr5wNKY6UuJ91hB0dedYfp5Kmq7+a2tIvQKOyO4UNfTCZAMa+Gou2RTDzhbCRph3gCkPmp/EAh68qsbdrdODvvfeL0w51eAukIWtbl7VL3vexpMNPuZcdf1liEmF0x80iLk5WqHlY56sFnjHyFLoBL5F73jHGXTQDF+SzHkJMA8O/Ohd1XJmIt6RFxDASlp/Sz5ebG2b3qTEgde10UtRuC6GXqnCXVnusdxBrRS6zNQeSjdTnWGqo1ugUQL+NEb9OwIR4SuL3V6PfR59sZXrQD0f7JoRhoEnODVBZLBdXrRbveIMo0g2PCdyBcmn0PRwWxLUJkbEW1KHduUeD2VqDQ=
    on:
      tags: true
